// <auto-generated />
using System;
using LexiMotion.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexiMotion.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909024915_InitSocialPost")]
    partial class InitSocialPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexiMotion.Web.Data.SocialPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfidenceScores")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalEmotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NegationDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("PredictedEmotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SarcasmDetected")
                        .HasColumnType("boolean");

                    b.Property<float>("SarcasmProbability")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SocialPost", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
