--
-- PostgreSQL database dump
--

\restrict SRzsd88hzGjXKvlAOkWc0DvxgIhQQpfE6xZIIFZ5Hh3qcYnDQ4JVIfX5cAHdATw

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-10 09:06:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4896 (class 1262 OID 16388)
-- Name: LexiMotionDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "LexiMotionDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Philippines.1252';


ALTER DATABASE "LexiMotionDB" OWNER TO postgres;

\unrestrict SRzsd88hzGjXKvlAOkWc0DvxgIhQQpfE6xZIIFZ5Hh3qcYnDQ4JVIfX5cAHdATw
\connect "LexiMotionDB"
\restrict SRzsd88hzGjXKvlAOkWc0DvxgIhQQpfE6xZIIFZ5Hh3qcYnDQ4JVIfX5cAHdATw

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 24610)
-- Name: SocialPost; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SocialPost" (
    "Id" integer NOT NULL,
    "InputText" text NOT NULL,
    "PredictedEmotion" text NOT NULL,
    "ConfidenceScores" jsonb NOT NULL,
    "NegationDetected" boolean NOT NULL,
    "SarcasmDetected" boolean NOT NULL,
    "SarcasmProbability" real NOT NULL,
    "FinalEmotion" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."SocialPost" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 24609)
-- Name: SocialPost_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SocialPost" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SocialPost_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4745 (class 2606 OID 24616)
-- Name: SocialPost PK_SocialPost; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SocialPost"
    ADD CONSTRAINT "PK_SocialPost" PRIMARY KEY ("Id");


-- Completed on 2025-09-10 09:06:16

--
-- PostgreSQL database dump complete
--

\unrestrict SRzsd88hzGjXKvlAOkWc0DvxgIhQQpfE6xZIIFZ5Hh3qcYnDQ4JVIfX5cAHdATw

